import { type JSX } from 'solid-js'
import { K8S_ICONS, type K8sIconPaint } from './k8sIconPaths'

// Topology cards used to identify a resource by its uppercase KIND text alone (POD, DEPLOYMENT,
// REPLICASET, …). At small font size and in a dense graph, similarly-prefixed names ("Deployment"
// vs "DaemonSet") read identically in peripheral vision; a distinct glyph per kind makes types
// recognizable without reading.
//
// The glyphs are the official Kubernetes resource pictograms as curated by Argo CD — glyph-only,
// without the icon set's heptagon frame or blue background (© The Argo Project Authors / The
// Kubernetes Authors, Apache-2.0; attribution and license text in NOTICE). They are embedded as
// flattened path data in k8sIconPaths.ts, regenerated by web/scripts/import-k8s-icons.mjs. WHY
// this source: operators already know these exact shapes from the Kubernetes docs and the Argo CD
// resource tree, so recognition is instant — and the glyph-only form keeps kd's icon language:
// monochrome via currentColor in the dim text color, so color stays reserved for health (which
// lives on the card border/stripe, never the icon).
//
// Each entry returns SVG primitives that compose inside a 14x14 viewBox via <g> at the card's
// top-left. Fragments only (no nested <svg>) — the card SVG provides the coordinate space.
// Official glyphs self-declare fill/stroke per path (reading color from currentColor); the
// kd-drawn glyphs below (kinds with no upstream artwork) inherit the container's stroke rules
// (.node-icon, .drawer-kind-icon, .kind-chip-icon).

// Explicit per-path paint values on official glyphs, including the defaults: containers set a
// dim stroke + rounded caps for the kd-drawn glyphs, and inheriting those would outline filled
// silhouettes and fuse fine dash patterns (Namespace's dashed border) into solid lines.
const paintPath = (p: K8sIconPaint, color: string): JSX.Element => (
  <path
    d={p.d}
    fill={p.fill ? color : 'none'}
    fill-rule={p.fillRule}
    stroke={p.stroke ? color : 'none'}
    stroke-width={p.stroke ? p.strokeWidth : undefined}
    stroke-dasharray={p.strokeDasharray}
    stroke-linecap={p.stroke ? (p.strokeLinecap ?? 'butt') : undefined}
    stroke-linejoin={p.stroke ? (p.strokeLinejoin ?? 'miter') : undefined}
  />
)

// A hole primitive erases its region from everything painted before it: the upstream artwork
// paints these white assuming a white canvas (see k8sIconPaths.ts), but kd cards are
// health-tinted, so the erased region must show the real background. Each hole wraps the
// accumulated output in a luminance mask — literal white keeps, the black hole shape erases —
// so themes never affect it. Mask ids are document-global and the same glyph renders on many
// cards at once, hence the counter. The explicit stroke="none" on the keep-rect matters: the
// mask's content still inherits the container's dim stroke, which would etch a gray (= partially
// transparent) border into the mask.
let maskSeq = 0
const renderGlyph = (paints: K8sIconPaint[]): JSX.Element => {
  let acc: JSX.Element[] = []
  for (const p of paints) {
    if (p.hole) {
      if (acc.length === 0) continue
      const id = `kicon-hole-${maskSeq++}`
      acc = [
        <g mask={`url(#${id})`}>
          <mask id={id} maskUnits="userSpaceOnUse" x="-2" y="-2" width="18" height="18">
            <rect x="-2" y="-2" width="18" height="18" fill="#ffffff" stroke="none" />
            {paintPath(p, '#000000')}
          </mask>
          {acc}
        </g>,
      ]
    } else {
      acc.push(paintPath(p, 'currentColor'))
    }
  }
  return <>{acc}</>
}

const official = Object.fromEntries(
  Object.entries(K8S_ICONS).map(([kind, paints]) => [kind, () => renderGlyph(paints)]),
)

const icons: Record<string, () => JSX.Element> = {
  ...official,
  // Server box with ports — a Node is a worker machine. kd-drawn: Argo CD's app tree never shows
  // a Node so its set has no glyph, and the Kubernetes Icons Set's node pictogram is a heptagon
  // that reads as k8s branding rather than "a machine".
  Node: () => (
    <>
      <rect x="2" y="3" width="10" height="8" rx="1" />
      <line x1="2" y1="7" x2="12" y2="7" />
      <circle cx="4" cy="5" r="0.5" fill="currentColor" />
      <circle cx="4" cy="9" r="0.5" fill="currentColor" />
    </>
  ),
  // Plug shape — an APIService extends the API surface.
  APIService: () => (
    <>
      <rect x="3.5" y="3.5" width="7" height="5" rx="0.5" />
      <line x1="5" y1="3.5" x2="5" y2="2" />
      <line x1="9" y1="3.5" x2="9" y2="2" />
      <line x1="7" y1="8.5" x2="7" y2="11.5" />
    </>
  ),
  // Disk stack with a small driver glyph — CSINode reports CSI driver presence on a node.
  CSINode: () => (
    <>
      <ellipse cx="7" cy="3.5" rx="4" ry="1.2" />
      <line x1="3" y1="3.5" x2="3" y2="8.5" />
      <line x1="11" y1="3.5" x2="11" y2="8.5" />
      <path d="M 3 8.5 a 4 1.2 0 0 0 8 0" fill="none" />
      <line x1="5.5" y1="11" x2="8.5" y2="11" />
    </>
  ),
  // Disk + lock chip — CSIDriver is a cluster-wide storage driver registration.
  CSIDriver: () => (
    <>
      <ellipse cx="6" cy="3.5" rx="3.5" ry="1.2" />
      <line x1="2.5" y1="3.5" x2="2.5" y2="9.5" />
      <line x1="9.5" y1="3.5" x2="9.5" y2="9.5" />
      <path d="M 2.5 9.5 a 3.5 1.2 0 0 0 7 0" fill="none" />
      <rect x="9" y="6" width="3.5" height="3" rx="0.5" />
    </>
  ),
  // Filter funnel — a Mutating/ValidatingWebhookConfiguration intercepts API requests.
  MutatingWebhookConfiguration: () => (
    <path d="M 2 3 L 12 3 L 9 7 L 9 11 L 5 11 L 5 7 z" />
  ),
  ValidatingWebhookConfiguration: () => (
    <>
      <path d="M 2 3 L 12 3 L 9 7 L 9 11 L 5 11 L 5 7 z" />
      <path d="M 5.5 5.5 L 7 7 L 9 4.5" stroke-width="1.5" />
    </>
  ),
  // Shield — a PDB protects availability during disruptions.
  PodDisruptionBudget: () => (
    <path d="M 7 2 L 11.5 4 L 11.5 8 C 11.5 10 7 12 7 12 C 7 12 2.5 10 2.5 8 L 2.5 4 z" />
  ),
  // Ladder rungs — a PriorityClass orders scheduling priority.
  PriorityClass: () => (
    <>
      <line x1="3.5" y1="3" x2="3.5" y2="12" />
      <line x1="10.5" y1="3" x2="10.5" y2="12" />
      <line x1="3.5" y1="5" x2="10.5" y2="5" />
      <line x1="3.5" y1="7.5" x2="10.5" y2="7.5" />
      <line x1="3.5" y1="10" x2="10.5" y2="10" />
    </>
  ),
}

// kindInitials derives a short badge text for kinds without any icon: the first two capitals of
// a CamelCase kind ("IngressRoute" → "IR"), one capital when that's all there is ("Certificate"
// → "C"), else the upcased first letter. Two letters max — more turns to mush at card size.
export function kindInitials(kind: string): string {
  const caps = kind.match(/[A-Z]/g) ?? []
  if (caps.length > 0) return caps.slice(0, 2).join('')
  return (kind[0] ?? '?').toUpperCase()
}

// Fallback for kinds without a dedicated icon (arbitrary CRs, future additions): an Argo CD-style
// generated badge — the kind's initials in a circle — so an unknown kind still shows something
// identifying rather than an anonymous empty square. The circle inherits the container's stroke
// like the kd-drawn glyphs; the text paints explicitly (containers set fill: none, and an
// inherited stroke would fuzz letterforms this small).
const fallback = (kind: string) => () => {
  const initials = kindInitials(kind)
  return (
    <>
      <circle cx="7" cy="7" r="5.5" />
      <text
        x="7"
        y="7"
        text-anchor="middle"
        dominant-baseline="central"
        font-size={initials.length > 1 ? '5' : '6'}
        font-weight="600"
        fill="currentColor"
        stroke="none"
      >
        {initials}
      </text>
    </>
  )
}

// kindIcon renders the SVG fragment for the given kind, or the generated fallback badge. The
// caller is expected to wrap it in a <g> with the desired stroke/fill/transform.
export function kindIcon(kind: string): JSX.Element {
  return (icons[kind] ?? fallback(kind))()
}

// hasKindIcon reports whether a kind has a dedicated icon (vs the generic fallback). Useful for
// tests that assert coverage of currently-emitted kinds without snapshotting visuals.
export function hasKindIcon(kind: string): boolean {
  return kind in icons
}

// kindFromRef extracts the leading kind from a binding's roleRef string ("Role/foo",
// "ClusterRole/bar") or a binding-subject string ("User: x", "Group: g", "ServiceAccount: ns/sa").
// Returns "" if neither shape matches, so a caller can decide whether to render an icon at all.
export function kindFromRef(ref: string): string {
  const slash = ref.indexOf('/')
  const colon = ref.indexOf(':')
  // Subject lines use "Kind: rest"; roleRef uses "Kind/rest". Pick the earlier separator (if any).
  if (colon !== -1 && (slash === -1 || colon < slash)) return ref.slice(0, colon).trim()
  if (slash !== -1) return ref.slice(0, slash).trim()
  return ''
}
